// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SOM.BDD.Features.Ferramenta.Midia
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("3.1.3 - Buscar Mídia", new string[] {
            "kill_Driver",
            "Midia",
            "BuscarMidia"}, SourceFile="Features\\Ferramenta\\Midia\\3.1.3 - Buscar Mídia.feature", SourceLine=6)]
    public partial class _3_1_3_BuscarMidiaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "3.1.3 - Buscar Mídia.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "3.1.3 - Buscar Mídia", null, ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver",
                        "Midia",
                        "BuscarMidia"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line 10
    testRunner.Given("que esteja logado no sistema SOM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
    testRunner.And("que esteja na tela consultar mídia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Buscar Mídia com campo em branco.", new string[] {
                "chrome",
                "BuscarMidiaCT01"}, SourceLine=13)]
        public virtual void BuscarMidiaComCampoEmBranco_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar Mídia com campo em branco.", null, new string[] {
                        "chrome",
                        "BuscarMidiaCT01"});
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 15
    testRunner.When("realizo uma pesquisa sem preencher o campo buscar midia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 16
    testRunner.Then("visualizo a grid com os campos Midia, Ar e Ativa preenchidos com todas as mídias." +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void BuscarMidiaInexistente_(string buscarMidia, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "BuscarMidiaCT02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar Mídia inexistente.", null, @__tags);
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 20
      testRunner.When(string.Format("realizo uma busca preenchendo o campo {0}", buscarMidia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 21
      testRunner.Then(string.Format("visualizo a mensagem de dados encontrados {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Buscar Mídia inexistente., \"Novo Teste\"", new string[] {
                "chrome",
                "BuscarMidiaCT02"}, SourceLine=24)]
        public virtual void BuscarMidiaInexistente__NovoTeste()
        {
#line 19
this.BuscarMidiaInexistente_("\"Novo Teste\"", "\"Dados não encontratos\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Buscar Mídia pelo filtro Ativa.", new string[] {
                "chrome",
                "BuscarMidiaCT03"}, SourceLine=27)]
        public virtual void BuscarMidiaPeloFiltroAtiva_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar Mídia pelo filtro Ativa.", null, new string[] {
                        "chrome",
                        "BuscarMidiaCT03"});
#line 28
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 29
      testRunner.When("realizo uma busca com filtro Ativa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 30
      testRunner.Then("visualizo a grid com os campos Midia, Ar e Ativa preenchidos com todas as mídias." +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void BuscarMidiaPeloFiltroARComSucesso_(string aR, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "BuscarMidiaCT04"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar Mídia pelo filtro AR com sucesso.", null, @__tags);
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 34
      testRunner.When(string.Format("realizo uma busca selecionando o campo Ar {0}", aR), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 35
      testRunner.Then("visualizo a grid com os campos Midia, Ar e Ativa preenchidos com todas as mídias." +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Buscar Mídia pelo filtro AR com sucesso., \"450005\"", new string[] {
                "chrome",
                "BuscarMidiaCT04"}, SourceLine=38)]
        public virtual void BuscarMidiaPeloFiltroARComSucesso__450005()
        {
#line 33
this.BuscarMidiaPeloFiltroARComSucesso_("\"450005\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscarMidiaPeloFiltroARInexistente_(string aR, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "BuscarMidiaCT05"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar Mídia pelo filtro AR inexistente.", null, @__tags);
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 43
      testRunner.When(string.Format("realizo uma busca selecionando o campo Ar {0}", aR), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 44
      testRunner.Then(string.Format("visualizo a mensagem de dados encontrados {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Buscar Mídia pelo filtro AR inexistente., \"123456\"", new string[] {
                "chrome",
                "BuscarMidiaCT05"}, SourceLine=47)]
        public virtual void BuscarMidiaPeloFiltroARInexistente__123456()
        {
#line 42
this.BuscarMidiaPeloFiltroARInexistente_("\"123456\"", "\"Dados não encontratos\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
