// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SOM.BDD.Features.Obra.DDA
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("3.1.4 - Alterações de DDA - Contato", new string[] {
            "chrome",
            "kill_Driver",
            "DDA",
            "AlteracaoDeContatoDDA"}, SourceFile="Features\\Obra\\DDA\\3.1.4 - Alteração de DDA (Contato).feature", SourceLine=6)]
    public partial class _3_1_4_AlteracoesDeDDA_ContatoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "3.1.4 - Alteração de DDA (Contato).feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "3.1.4 - Alterações de DDA - Contato", null, ProgrammingLanguage.CSharp, new string[] {
                        "chrome",
                        "kill_Driver",
                        "DDA",
                        "AlteracaoDeContatoDDA"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line 10
    testRunner.Given("que esteja logado no sistema SOM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
    testRunner.And("que estou com a tela Novo Cadastro de DDA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        public virtual void AlteracaoTelefoneDeContatoComSucesso(string telefone, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "AlteracaoContatoDeDDACT01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alteração Telefone de contato com sucesso", null, @__tags);
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 15
      testRunner.Given("que tenho um DDA cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
   testRunner.And(string.Format("altero o telefone {0}", telefone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
      testRunner.Then(string.Format("visualizo a mensagem do DDA alterado com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alteração Telefone de contato com sucesso, \"2227017569\"", new string[] {
                "chrome",
                "AlteracaoContatoDeDDACT01"}, SourceLine=20)]
        public virtual void AlteracaoTelefoneDeContatoComSucesso_2227017569()
        {
#line 14
this.AlteracaoTelefoneDeContatoComSucesso("\"2227017569\"", "\"Registro editado com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AlteracaoDoEmailDeAutorizacaoDeContatoComSucesso(string email, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "AlteracaoContatoDeDDACT02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alteração do email de autorizacao de contato com sucesso", null, @__tags);
#line 24
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 25
      testRunner.Given("que tenho um DDA cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 26
   testRunner.And(string.Format("altero o email {0}", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
   testRunner.Then(string.Format("visualizo a mensagem do DDA alterado com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alteração do email de autorizacao de contato com sucesso, \"teste@teste.com\"", new string[] {
                "chrome",
                "AlteracaoContatoDeDDACT02"}, SourceLine=30)]
        public virtual void AlteracaoDoEmailDeAutorizacaoDeContatoComSucesso_TesteTeste_Com()
        {
#line 24
this.AlteracaoDoEmailDeAutorizacaoDeContatoComSucesso("\"teste@teste.com\"", "\"Registro editado com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AlteracaoDaFlagDeAutorizacaoDeE_Mail(string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "AlteracaoContatoDeDDACT03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alteracao da flag de Autorizacao de E-mail", null, @__tags);
#line 34
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 35
      testRunner.Given("que tenho um DDA cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 36
      testRunner.And("altero o a flag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 37
      testRunner.Then(string.Format("visualizo a mensagem do DDA alterado com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alteracao da flag de Autorizacao de E-mail, \"Registro editado com sucesso.\"", new string[] {
                "chrome",
                "AlteracaoContatoDeDDACT03"}, SourceLine=40)]
        public virtual void AlteracaoDaFlagDeAutorizacaoDeE_Mail_RegistroEditadoComSucesso_()
        {
#line 34
this.AlteracaoDaFlagDeAutorizacaoDeE_Mail("\"Registro editado com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
