// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SOM.BDD.Features.Pagamento.TabelaDePreco
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("6.5.1 - Cadastro de Tabela de Preços", new string[] {
            "kill_Driver",
            "CadastroDeTabelaDePreco"}, SourceFile="Features\\Pagamento\\Tabela de Preço\\6.5.1 - Cadastro de Tabela de Precos.feature", SourceLine=6)]
    public partial class _6_5_1_CadastroDeTabelaDePrecosFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "6.5.1 - Cadastro de Tabela de Precos.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "6.5.1 - Cadastro de Tabela de Preços", null, ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver",
                        "CadastroDeTabelaDePreco"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line 10
 testRunner.Given("que esteja logado no sistema SOM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        public virtual void CadastrarNovaTabelaDePrecoComSucesso(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar nova tabela de preço com sucesso", null, @__tags);
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 14
 testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 15
 testRunner.When(string.Format("cadastro uma nova tabela de preço {0}, {1}, {2}, {3}, {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 16
 testRunner.Then(string.Format("visualizo a mensagem de tabela de preço criada com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar nova tabela de preço com sucesso, \"Tabela Teste 100\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT01"}, SourceLine=19)]
        public virtual void CadastrarNovaTabelaDePrecoComSucesso_TabelaTeste100()
        {
#line 13
this.CadastrarNovaTabelaDePrecoComSucesso("\"Tabela Teste 100\"", "\"01/01/2000\"", "\"01/01/2001\"", "\"GLOBONEWS\"", "\"Não\"", "\"Tabela criada com sucesso\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidarCamposObrigatoriosComSucesso(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar campos obrigatórios com sucesso", null, @__tags);
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 24
 testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
 testRunner.When(string.Format("cadastro uma nova tabela sem preencher os campos obrigatorios {0}, {1}, {2}, {3}," +
                        " {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 26
    testRunner.Then("visualizo os campos destacados para preenchimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validar campos obrigatórios com sucesso, \" \"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT02"}, SourceLine=29)]
        public virtual void ValidarCamposObrigatoriosComSucesso_()
        {
#line 23
this.ValidarCamposObrigatoriosComSucesso("\" \"", "\" \"", "\" \"", "\" \"", "\" \"", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidarDataInvalidaComSucesso(string inicioVigencia, string fimVigencia, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar data inválida com sucesso", null, @__tags);
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 34
 testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 35
    testRunner.When(string.Format("cadastro uma nova tabela preenchendo os campos {0} e {1} com datas inválidas", inicioVigencia, fimVigencia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 36
    testRunner.Then("visualizo os campos destacados para preenchimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validar data inválida com sucesso, \"31-31-8392\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT03"}, SourceLine=39)]
        public virtual void ValidarDataInvalidaComSucesso_31_31_8392()
        {
#line 33
this.ValidarDataInvalidaComSucesso("\"31-31-8392\"", "\"90-90-21847\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidarMensagemDeErroAoCadastrarTabelasIguais(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT04"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar mensagem de erro ao cadastrar tabelas iguais", null, @__tags);
#line 43
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 44
 testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 45
 testRunner.When(string.Format("cadastro uma nova tabela de preço com o mesmo nome e periodo de vigencia de uma t" +
                        "abela previamente cadastrada {0}, {1}, {2}, {3}, {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 46
    testRunner.Then(string.Format("visualizo a mensagem de critica ao tentar salvar a tabela {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validar mensagem de erro ao cadastrar tabelas iguais, \"Tabela Teste 100\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT04"}, SourceLine=49)]
        public virtual void ValidarMensagemDeErroAoCadastrarTabelasIguais_TabelaTeste100()
        {
#line 43
this.ValidarMensagemDeErroAoCadastrarTabelasIguais("\"Tabela Teste 100\"", "\"01/01/2000\"", "\"01/01/2001\"", "\"TV\"", "\"Não\"", "\"Já existe uma tabela cadastrada com este nome e data de vigência.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void CriarTabelasComOMesmoPeriodoDeVigencia(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT05"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar tabelas com o mesmo período de vigência", null, @__tags);
#line 53
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 54
    testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 55
 testRunner.When(string.Format("cadastro uma nova tabela de preço com o mesmo periodo de vigencia de uma tabela p" +
                        "reviamente cadastrada {0}, {1}, {2}, {3}, {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 56
    testRunner.Then(string.Format("visualizo a mensagem de critica ao tentar salvar a tabela {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Criar tabelas com o mesmo período de vigência, \"Tabela Teste 102\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT05"}, SourceLine=59)]
        public virtual void CriarTabelasComOMesmoPeriodoDeVigencia_TabelaTeste102()
        {
#line 53
this.CriarTabelasComOMesmoPeriodoDeVigencia("\"Tabela Teste 102\"", "\"01/01/2000\"", "\"01/01/2001\"", "\"TV\"", "\"Não\"", "\"Já existe uma tabela para esta mídia com a data de vigência informada.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaDramaturgiaDiariaDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT06"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Dramaturgia Diária da tabela nacional com sucesso", null, @__tags);
#line 67
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 68
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 69
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 70
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Dramaturgia Diária da tabela nacional com sucesso, \"DRAMATU" +
            "RGIA DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT06"}, SourceLine=73)]
        public virtual void AdicionarValorAAbaDramaturgiaDiariaDaTabelaNacionalComSucesso_DRAMATURGIADIARIA()
        {
#line 67
this.AdicionarValorAAbaDramaturgiaDiariaDaTabelaNacionalComSucesso("\"DRAMATURGIA DIÁRIA\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaDramaturgiaSemanalDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT07"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Dramaturgia Semanal da tabela nacional com sucesso", null, @__tags);
#line 77
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 78
 testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 79
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 80
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Dramaturgia Semanal da tabela nacional com sucesso, \"DRAMAT" +
            "URGIA SEMANAL\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT07"}, SourceLine=83)]
        public virtual void AdicionarValorAAbaDramaturgiaSemanalDaTabelaNacionalComSucesso_DRAMATURGIASEMANAL()
        {
#line 77
this.AdicionarValorAAbaDramaturgiaSemanalDaTabelaNacionalComSucesso("\"DRAMATURGIA SEMANAL\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaEsporteDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT08"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Esporte da tabela nacional com sucesso", null, @__tags);
#line 87
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 88
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 89
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 90
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Esporte da tabela nacional com sucesso, \"ESPORTE\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT08"}, SourceLine=93)]
        public virtual void AdicionarValorAAbaEsporteDaTabelaNacionalComSucesso_ESPORTE()
        {
#line 87
this.AdicionarValorAAbaEsporteDaTabelaNacionalComSucesso("\"ESPORTE\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaJornalismoDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT09"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Jornalismo da tabela nacional com sucesso", null, @__tags);
#line 97
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 98
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 99
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 100
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Jornalismo da tabela nacional com sucesso, \"JORNALISMO\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT09"}, SourceLine=103)]
        public virtual void AdicionarValorAAbaJornalismoDaTabelaNacionalComSucesso_JORNALISMO()
        {
#line 97
this.AdicionarValorAAbaJornalismoDaTabelaNacionalComSucesso("\"JORNALISMO\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaVariedadeDiariaDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Variedade Diária da tabela nacional com sucesso", null, @__tags);
#line 107
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 108
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 109
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 110
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Variedade Diária da tabela nacional com sucesso, \"VARIEDADE" +
            " DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT10"}, SourceLine=113)]
        public virtual void AdicionarValorAAbaVariedadeDiariaDaTabelaNacionalComSucesso_VARIEDADEDIARIA()
        {
#line 107
this.AdicionarValorAAbaVariedadeDiariaDaTabelaNacionalComSucesso("\"VARIEDADE DIÁRIA\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaVariedadeSemanalDaTabelaNacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT11"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Variedade Semanal da tabela nacional com sucesso", null, @__tags);
#line 117
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 118
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 119
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 120
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Variedade Semanal da tabela nacional com sucesso, \"VARIEDAD" +
            "E SEMANAL\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT11"}, SourceLine=123)]
        public virtual void AdicionarValorAAbaVariedadeSemanalDaTabelaNacionalComSucesso_VARIEDADESEMANAL()
        {
#line 117
this.AdicionarValorAAbaVariedadeSemanalDaTabelaNacionalComSucesso("\"VARIEDADE SEMANAL\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaDramaturgiaDiariaDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT12"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Dramaturgia Diária da tabela internacional com sucesso", null, @__tags);
#line 127
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 128
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 129
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 130
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Dramaturgia Diária da tabela internacional com sucesso, \"DR" +
            "AMATURGIA DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT12"}, SourceLine=133)]
        public virtual void AdicionarValorAAbaDramaturgiaDiariaDaTabelaInternacionalComSucesso_DRAMATURGIADIARIA()
        {
#line 127
this.AdicionarValorAAbaDramaturgiaDiariaDaTabelaInternacionalComSucesso("\"DRAMATURGIA DIÁRIA\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaDramaturgiaSemanalDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT13"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Dramaturgia Semanal da tabela internacional com sucesso", null, @__tags);
#line 137
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 138
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 139
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 140
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Dramaturgia Semanal da tabela internacional com sucesso, \"D" +
            "RAMATURGIA SEMANAL\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT13"}, SourceLine=143)]
        public virtual void AdicionarValorAAbaDramaturgiaSemanalDaTabelaInternacionalComSucesso_DRAMATURGIASEMANAL()
        {
#line 137
this.AdicionarValorAAbaDramaturgiaSemanalDaTabelaInternacionalComSucesso("\"DRAMATURGIA SEMANAL\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaEsporteDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT14"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Esporte da tabela internacional com sucesso", null, @__tags);
#line 147
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 148
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 149
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 150
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Esporte da tabela internacional com sucesso, \"ESPORTE\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT14"}, SourceLine=153)]
        public virtual void AdicionarValorAAbaEsporteDaTabelaInternacionalComSucesso_ESPORTE()
        {
#line 147
this.AdicionarValorAAbaEsporteDaTabelaInternacionalComSucesso("\"ESPORTE\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaJornalismoDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT15"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Jornalismo da tabela internacional com sucesso", null, @__tags);
#line 157
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 158
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 159
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 160
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Jornalismo da tabela internacional com sucesso, \"JORNALISMO" +
            "\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT15"}, SourceLine=163)]
        public virtual void AdicionarValorAAbaJornalismoDaTabelaInternacionalComSucesso_JORNALISMO()
        {
#line 157
this.AdicionarValorAAbaJornalismoDaTabelaInternacionalComSucesso("\"JORNALISMO\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaVariedadeDiariaDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT16"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Variedade Diária da tabela internacional com sucesso", null, @__tags);
#line 167
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 168
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 169
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 170
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Variedade Diária da tabela internacional com sucesso, \"VARI" +
            "EDADE DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT16"}, SourceLine=173)]
        public virtual void AdicionarValorAAbaVariedadeDiariaDaTabelaInternacionalComSucesso_VARIEDADEDIARIA()
        {
#line 167
this.AdicionarValorAAbaVariedadeDiariaDaTabelaInternacionalComSucesso("\"VARIEDADE DIÁRIA\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void AdicionarValorAAbaVariedadeSemanalDaTabelaInternacionalComSucesso(string genero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT17"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar valor à aba Variedade Semanal da tabela internacional com sucesso", null, @__tags);
#line 177
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 178
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 179
    testRunner.When(string.Format("preencho com valor válido os tipos de sincronização internacionais {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 180
    testRunner.Then(string.Format("visualizo a mensagem de itens adicionados com sucesso à tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Adicionar valor à aba Variedade Semanal da tabela internacional com sucesso, \"VAR" +
            "IEDADE SEMANAL\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT17"}, SourceLine=183)]
        public virtual void AdicionarValorAAbaVariedadeSemanalDaTabelaInternacionalComSucesso_VARIEDADESEMANAL()
        {
#line 177
this.AdicionarValorAAbaVariedadeSemanalDaTabelaInternacionalComSucesso("\"VARIEDADE SEMANAL\"", "\"Itens foram salvos com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidarNaoAceitacaoDeValoresNegativosNaTabelaNacional(string genero, string abertura, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT18"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar não aceitação de valores negativos na tabela nacional", null, @__tags);
#line 187
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 188
 testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 189
 testRunner.When(string.Format("preencho com valor negativo no tipo de sincronização {0}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 190
    testRunner.Then(string.Format("visualizo o campo voltar a apresentar o ultimo valor valido da tabela de preço {0" +
                        "}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validar não aceitação de valores negativos na tabela nacional, \"DRAMATURGIA DIÁRI" +
            "A\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT18"}, SourceLine=193)]
        public virtual void ValidarNaoAceitacaoDeValoresNegativosNaTabelaNacional_DRAMATURGIADIARIA()
        {
#line 187
this.ValidarNaoAceitacaoDeValoresNegativosNaTabelaNacional("\"DRAMATURGIA DIÁRIA\"", "\"-1\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidarNaoAceitacaoDeValoresNegativosNaTabelaInternacional(string genero, string abertura, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT19"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar não aceitação de valores negativos na tabela internacional", null, @__tags);
#line 197
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 198
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 199
    testRunner.When(string.Format("preencho com valor negativo no tipo de sincronização internacional {0}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 200
    testRunner.Then(string.Format("visualizo o campo voltar a apresentar o ultimo valor valido da tabela de preço in" +
                        "ternacional {0}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validar não aceitação de valores negativos na tabela internacional, \"DRAMATURGIA " +
            "DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT19"}, SourceLine=203)]
        public virtual void ValidarNaoAceitacaoDeValoresNegativosNaTabelaInternacional_DRAMATURGIADIARIA()
        {
#line 197
this.ValidarNaoAceitacaoDeValoresNegativosNaTabelaInternacional("\"DRAMATURGIA DIÁRIA\"", "\"-1\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void VerificarMensagemDeErroAoCadastrarValoresDaTabelaNacionalComValoresMuitoAltos(string genero, string abertura, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT20"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verificar mensagem de erro ao cadastrar valores da tabela nacional com valores mu" +
                    "ito altos", null, @__tags);
#line 207
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 208
 testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 209
 testRunner.When(string.Format("preencho com valor muito alto no tipo de sincronização {0}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 210
 testRunner.Then(string.Format("visualizo a mensagem de erro ao tentar salvar a tabela de preço {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verificar mensagem de erro ao cadastrar valores da tabela nacional com valores mu" +
            "ito altos, \"DRAMATURGIA DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT20"}, SourceLine=213)]
        public virtual void VerificarMensagemDeErroAoCadastrarValoresDaTabelaNacionalComValoresMuitoAltos_DRAMATURGIADIARIA()
        {
#line 207
this.VerificarMensagemDeErroAoCadastrarValoresDaTabelaNacionalComValoresMuitoAltos("\"DRAMATURGIA DIÁRIA\"", "\"837402357383485742308674367409\"", "\"Ocorreu um erro ao salvar o item.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void VerificarMensagemDeErroAoCadastrarValoresDaTabelaInternacionalComValoresMuitoAltos(string genero, string abertura, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT21"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verificar mensagem de erro ao cadastrar valores da tabela internacional com valor" +
                    "es muito altos", null, @__tags);
#line 217
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 218
    testRunner.Given(string.Format("que estou na tela de detalhes da tabela de preço internacional {0}", genero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 219
    testRunner.When(string.Format("preencho com valor muito alto no tipo de sincronização internacional {0}, {1}", genero, abertura), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 220
 testRunner.Then(string.Format("visualizo a mensagem de erro ao tentar salvar a tabela de preço internacional {0}" +
                        "", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verificar mensagem de erro ao cadastrar valores da tabela internacional com valor" +
            "es muito altos, \"DRAMATURGIA DIÁRIA\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT21"}, SourceLine=223)]
        public virtual void VerificarMensagemDeErroAoCadastrarValoresDaTabelaInternacionalComValoresMuitoAltos_DRAMATURGIADIARIA()
        {
#line 217
this.VerificarMensagemDeErroAoCadastrarValoresDaTabelaInternacionalComValoresMuitoAltos("\"DRAMATURGIA DIÁRIA\"", "\"837402357383485742308674367409\"", "\"Ocorreu um erro ao salvar o item.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void SairDaTelaSemSalvarCadastroDeTabela(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT22"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sair da tela sem salvar cadastro de tabela", null, @__tags);
#line 227
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 228
 testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 229
 testRunner.When(string.Format("cancelo o cadastro de uma nova tabela de preço {0}, {1}, {2}, {3}, {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 230
 testRunner.Then("visualizo a tela de busca por tabela de preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Sair da tela sem salvar cadastro de tabela, \"Tabela Teste 110\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT22"}, SourceLine=233)]
        public virtual void SairDaTelaSemSalvarCadastroDeTabela_TabelaTeste110()
        {
#line 227
this.SairDaTelaSemSalvarCadastroDeTabela("\"Tabela Teste 110\"", "\"01/01/2000\"", "\"01/01/2001\"", "\" \"", "\"Não\"", "\"Tabela criada com sucesso\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void SalvarTabelaSemMidiaComSucesso(string nome, string inicioVigencia, string fimVigencia, string midia, string padrao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeTabelaDePrecoCT23"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Salvar tabela sem mídia com sucesso", null, @__tags);
#line 237
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
this.FeatureBackground();
#line 238
    testRunner.Given("que estou na tela de cadastro de Tabela de Preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 239
 testRunner.When(string.Format("cadastro uma nova tabela de preço {0}, {1}, {2}, {3}, {4}", nome, inicioVigencia, fimVigencia, midia, padrao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 240
 testRunner.Then(string.Format("visualizo a mensagem de tabela de preço criada com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Salvar tabela sem mídia com sucesso, \"Tabela Teste 110\"", new string[] {
                "chrome",
                "CadastroDeTabelaDePrecoCT23"}, SourceLine=243)]
        public virtual void SalvarTabelaSemMidiaComSucesso_TabelaTeste110()
        {
#line 237
this.SalvarTabelaSemMidiaComSucesso("\"Tabela Teste 110\"", "\"01/01/2000\"", "\"01/01/2001\"", "\" \"", "\"Não\"", "\"Tabela criada com sucesso\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
