// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SOM.BDD.Features.Produto.Capitulo
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("4.1.2 - Cadastrar capítulos na criação do produto", new string[] {
            "kill_Driver",
            "Capitulo",
            "CadastroDeCapitulo"}, Description="Como um usuário com permissão de cadastrar capítulos\r\nEu quero poder cadastrar as" +
        " informações de capítulo para um produto já cadastrado\r\nPara que possa utilizar " +
        "os dados no cadastro associada ao produto", SourceFile="Features\\Produto\\Capitulo\\4.1.2 - Cadastrar Capítulo.feature", SourceLine=5)]
    public partial class _4_1_2_CadastrarCapitulosNaCriacaoDoProdutoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "4.1.2 - Cadastrar Capítulo.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "4.1.2 - Cadastrar capítulos na criação do produto", "Como um usuário com permissão de cadastrar capítulos\r\nEu quero poder cadastrar as" +
                    " informações de capítulo para um produto já cadastrado\r\nPara que possa utilizar " +
                    "os dados no cadastro associada ao produto", ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver",
                        "Capitulo",
                        "CadastroDeCapitulo"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
#line 12
    testRunner.Given("que esteja logado no sistema SOM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        public virtual void CadastrarCapitulo(string produto, string capitulo, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeCapituloCT01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar capítulo", null, @__tags);
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
this.FeatureBackground();
#line 16
 testRunner.Given("que tenha um produto cadastrado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 17
 testRunner.And("que esteja na tela de cadastro de capitulos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.When(string.Format("cadastro um novo capitulo para o produto existente {0}, {1}", produto, capitulo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 19
 testRunner.Then(string.Format("visualizo a mensagem de capitulo cadastrado com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar capítulo, \"Aleatório\"", new string[] {
                "chrome",
                "CadastroDeCapituloCT01"}, SourceLine=22)]
        public virtual void CadastrarCapitulo_Aleatorio()
        {
#line 15
this.CadastrarCapitulo("\"Aleatório\"", "\"10\"", "\"Registro adicionado com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void CadastarCapituloEmLote(string produto, string capitulo, string geracaoLote, string quantidadeCapitulos, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeCapituloCT02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastar capítulo em lote", null, @__tags);
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
this.FeatureBackground();
#line 27
 testRunner.Given("que tenha um produto cadastrado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 28
 testRunner.And("que esteja na tela de cadastro de capitulos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.When(string.Format("cadastro capitulos em lote para o produto existente {0}, {1}, {2}, {3}", produto, capitulo, geracaoLote, quantidadeCapitulos), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 30
 testRunner.Then(string.Format("visualizo a mensagem de capitulo cadastrado com sucesso {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastar capítulo em lote, \"Aleatório\"", new string[] {
                "chrome",
                "CadastroDeCapituloCT02"}, SourceLine=33)]
        public virtual void CadastarCapituloEmLote_Aleatorio()
        {
#line 26
this.CadastarCapituloEmLote("\"Aleatório\"", "\"10\"", "\"Sim\"", "\"5\"", "\"Registro adicionado com sucesso.\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void CancelarCadastroDeCapitulo(string produto, string capitulo, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "CadastroDeCapituloCT03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelar cadastro de Capítulo", null, @__tags);
#line 37
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
this.FeatureBackground();
#line 38
    testRunner.Given("que tenha um produto cadastrado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 39
 testRunner.And("que esteja na tela de cadastro de capitulos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 40
 testRunner.When(string.Format("cancelo o cadastro de um novo capitulo para o produto existente {0}, {1}", produto, capitulo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 41
 testRunner.Then("visualizo a tela de busca de capitulo com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cancelar cadastro de Capítulo, \"Aleatório\"", new string[] {
                "chrome",
                "CadastroDeCapituloCT03"}, SourceLine=44)]
        public virtual void CancelarCadastroDeCapitulo_Aleatorio()
        {
#line 37
this.CancelarCadastroDeCapitulo("\"Aleatório\"", "\"10\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar capítulo sem preenchimento de campo obrigatório", new string[] {
                "chrome",
                "CadastroDeCapituloCT04"}, SourceLine=47)]
        public virtual void CadastrarCapituloSemPreenchimentoDeCampoObrigatorio()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar capítulo sem preenchimento de campo obrigatório", null, new string[] {
                        "chrome",
                        "CadastroDeCapituloCT04"});
#line 48
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
this.FeatureBackground();
#line 49
 testRunner.Given("que esteja na tela de cadastro de capitulos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 50
 testRunner.When("tento cadastrar um capítulo sem preencher os campos obrigatórios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 51
 testRunner.Then("visualizo os campos obrigatórios de cadastro de capítulo em destaque", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
