// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SOM.BDD.Features.Pagamento.Pedido
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("6.1.3 - Consultar Pedido", new string[] {
            "kill_Driver",
            "ConsultarPedido",
            "Pedidos"}, SourceFile="Features\\Pagamento\\Pedido\\6.1.3 - Consultar Pedido.feature", SourceLine=5)]
    public partial class _6_1_3_ConsultarPedidoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "6.1.3 - Consultar Pedido.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "6.1.3 - Consultar Pedido", null, ProgrammingLanguage.CSharp, new string[] {
                        "kill_Driver",
                        "ConsultarPedido",
                        "Pedidos"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line 9
 testRunner.Given("que esteja logado no sistema SOM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 10
 testRunner.And("que esteja na tela de consulta de pedidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        public virtual void BuscaSimplesPorNumero(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca simples por numero", null, @__tags);
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 14
    testRunner.When(string.Format("faco um busca simples por numero de pedido {0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 15
 testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca simples por numero, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT01"}, SourceLine=18)]
        public virtual void BuscaSimplesPorNumero_1001404()
        {
#line 13
this.BuscaSimplesPorNumero("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorObra(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Obra", null, @__tags);
#line 22
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 23
    testRunner.When(string.Format("faço uma busca avançada de pedido por obra {0}", obra), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Obra, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT02"}, SourceLine=27)]
        public virtual void BuscaPorObra_1001404()
        {
#line 22
this.BuscaPorObra("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorNumero(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT03"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Número", null, @__tags);
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 32
 testRunner.When(string.Format("faço uma busca avançada de pedido por número {0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 33
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Número, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT03"}, SourceLine=36)]
        public virtual void BuscaPorNumero_1001404()
        {
#line 31
this.BuscaPorNumero("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorProduto(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT04"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Produto", null, @__tags);
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 41
    testRunner.When(string.Format("faço uma busca avançada de pedido por produto {0}", produto), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 42
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Produto, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT04"}, SourceLine=45)]
        public virtual void BuscaPorProduto_1001404()
        {
#line 40
this.BuscaPorProduto("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPeriodoDeExibicao(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string dataInicial, string dataFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT05"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca Periodo de Exibição", null, @__tags);
#line 49
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 50
    testRunner.When(string.Format("faço uma busca avançada de pedido por periodo de exibição {0}, {1}, {2}", produto, dataInicial, dataFinal), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 51
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca Periodo de Exibição, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT05"}, SourceLine=54)]
        public virtual void BuscaPeriodoDeExibicao_1001404()
        {
#line 49
this.BuscaPeriodoDeExibicao("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", "\"10/10/2018\"", "\"10/10/2018\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorDataInicio(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string dataInicial, string dataFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT06"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Data início", null, @__tags);
#line 58
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 59
    testRunner.When(string.Format("faço uma busca avançada de pedido por data inicial {0}, {1}", produto, dataInicial), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 60
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Data início, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT06"}, SourceLine=63)]
        public virtual void BuscaPorDataInicio_1001404()
        {
#line 58
this.BuscaPorDataInicio("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", "\"10/10/2018\"", "\"10/10/2018\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorAutor(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string autor, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT07"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por autor", null, @__tags);
#line 67
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 68
    testRunner.When(string.Format("faço uma busca avançada de pedido por autor {0}", autor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 69
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por autor, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT07"}, SourceLine=72)]
        public virtual void BuscaPorAutor_1001404()
        {
#line 67
this.BuscaPorAutor("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", "\"Hiram1326096162\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorDDA(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string dDA, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT08"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por DDA", null, @__tags);
#line 76
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 77
    testRunner.When(string.Format("faço uma busca avançada de pedido por DDA {0}", dDA), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 78
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por DDA, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT08"}, SourceLine=81)]
        public virtual void BuscaPorDDA_1001404()
        {
#line 76
this.BuscaPorDDA("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", "\"Hildegard1167235435\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorMidiaADebitar(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT09"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Mídia a Debitar", null, @__tags);
#line 85
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 86
    testRunner.When(string.Format("faço uma busca avançada de pedido por Midia a Debitar {0}, {1}", numero, midiaADebitar), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 87
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Mídia a Debitar, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT09"}, SourceLine=90)]
        public virtual void BuscaPorMidiaADebitar_1001404()
        {
#line 85
this.BuscaPorMidiaADebitar("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorSincronismoGlobo(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Sincronismo Globo", null, @__tags);
#line 94
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 95
    testRunner.When(string.Format("faço uma busca avançada de pedido por Sincronismo {0}, {1}", numero, sincronismo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 96
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Sincronismo Globo, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT10"}, SourceLine=99)]
        public virtual void BuscaPorSincronismoGlobo_1001404()
        {
#line 94
this.BuscaPorSincronismoGlobo("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorStatus(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT11"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Status", null, @__tags);
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 104
    testRunner.When(string.Format("faço uma busca avançada de pedido por status e numero {0}, {1}", numero, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 105
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Status, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT11"}, SourceLine=108)]
        public virtual void BuscaPorStatus_1001404()
        {
#line 103
this.BuscaPorStatus("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorMidiaAutorizada(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string midiaAutorizada, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT12"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Mídia Autorizada", null, @__tags);
#line 112
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 113
    testRunner.When(string.Format("faço uma busca avançada de pedido por Midia Autorizada {0}, {1}", numero, midiaAutorizada), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 114
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Mídia Autorizada, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT12"}, SourceLine=117)]
        public virtual void BuscaPorMidiaAutorizada_1001404()
        {
#line 112
this.BuscaPorMidiaAutorizada("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", "\"GLOBONEWS\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void BuscaPorValorNegociado(string valorNegociado, string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT13"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por Valor Negociado", null, @__tags);
#line 121
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 122
 testRunner.When(string.Format("faço uma busca avançada de pedido por Valor Negociado e Número {0}, {1}", numero, valorNegociado), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 123
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Busca por Valor Negociado, \"Não\"", new string[] {
                "chrome",
                "ConsultarPedidoCT13"}, SourceLine=126)]
        public virtual void BuscaPorValorNegociado_Nao()
        {
#line 121
this.BuscaPorValorNegociado("\"Não\"", "\"1000565\"", "\"JORNAL NACIONAL\"", "\"\"", "\"999\"", "\"MUSICA DE TESTE 1\"", "\"TV\"", "\"ABERTURA\"", "\"R$ 800,00\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void VisualizacaoDeHistorico(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT14"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Visualização de Histórico", null, @__tags);
#line 130
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 131
 testRunner.When(string.Format("faço uma busca avançada de pedido por número {0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 132
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 133
 testRunner.And("visualizo as alterações feitas nos pedido ao acessar o historico", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Visualização de Histórico, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT14"}, SourceLine=136)]
        public virtual void VisualizacaoDeHistorico_1001404()
        {
#line 130
this.VisualizacaoDeHistorico("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void MelhoriasNaBuscaDePedido_CampoProduto(string produto, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT15"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Melhorias na busca de pedido - campo produto", null, @__tags);
#line 141
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 142
    testRunner.When(string.Format("faço uma busca avançada de pedido por produto {0}", produto), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 143
 testRunner.Then(string.Format("visualizo todos os pedidos que estejam vinculado ao produto buscado {0}", produto), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - campo produto, \"JORNAL NACIONAL\"", new string[] {
                "chrome",
                "ConsultarPedidoCT15"}, SourceLine=146)]
        public virtual void MelhoriasNaBuscaDePedido_CampoProduto_JORNALNACIONAL()
        {
#line 141
this.MelhoriasNaBuscaDePedido_CampoProduto("\"JORNAL NACIONAL\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - campo produto, \"Avis1816412639 Ozane1633164760\"", new string[] {
                "chrome",
                "ConsultarPedidoCT15"}, SourceLine=146)]
        public virtual void MelhoriasNaBuscaDePedido_CampoProduto_Avis1816412639Ozane1633164760()
        {
#line 141
this.MelhoriasNaBuscaDePedido_CampoProduto("\"Avis1816412639 Ozane1633164760\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void MelhoriasNaBuscaDePedido_CampoObra(string obra, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT16"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Melhorias na busca de pedido - campo obra", null, @__tags);
#line 151
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 152
    testRunner.When(string.Format("faço uma busca avançada de pedido por obra {0}", obra), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 153
 testRunner.Then(string.Format("visualizo todos os pedidos que estejam vinculado a obra buscada {0}", obra), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - campo obra, \"MUSICA DE TESTE 1\"", new string[] {
                "chrome",
                "ConsultarPedidoCT16"}, SourceLine=156)]
        public virtual void MelhoriasNaBuscaDePedido_CampoObra_MUSICADETESTE1()
        {
#line 151
this.MelhoriasNaBuscaDePedido_CampoObra("\"MUSICA DE TESTE 1\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - campo obra, \"Jonelle1677499510\"", new string[] {
                "chrome",
                "ConsultarPedidoCT16"}, SourceLine=156)]
        public virtual void MelhoriasNaBuscaDePedido_CampoObra_Jonelle1677499510()
        {
#line 151
this.MelhoriasNaBuscaDePedido_CampoObra("\"Jonelle1677499510\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void MelhoriasNaBuscaDePedido_Status(string status, string numero, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT17"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Melhorias na busca de pedido - Status", null, @__tags);
#line 161
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 162
    testRunner.When(string.Format("faço uma busca avançada de pedido por status e numero {0}, {1}", numero, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 163
    testRunner.Then(string.Format("visualizo todos os pedidos que estejam com status buscado {0}", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - Status, \"Em andamento\"", new string[] {
                "chrome",
                "ConsultarPedidoCT17"}, SourceLine=166)]
        public virtual void MelhoriasNaBuscaDePedido_Status_EmAndamento()
        {
#line 161
this.MelhoriasNaBuscaDePedido_Status("\"Em andamento\"", "\"1001451\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - Status, \"Cancelado\"", new string[] {
                "chrome",
                "ConsultarPedidoCT17"}, SourceLine=166)]
        public virtual void MelhoriasNaBuscaDePedido_Status_Cancelado()
        {
#line 161
this.MelhoriasNaBuscaDePedido_Status("\"Cancelado\"", "\"1001450\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - Status, \"Concluído\"", new string[] {
                "chrome",
                "ConsultarPedidoCT17"}, SourceLine=166)]
        public virtual void MelhoriasNaBuscaDePedido_Status_Concluido()
        {
#line 161
this.MelhoriasNaBuscaDePedido_Status("\"Concluído\"", "\"1000106\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void MelhoriasNaBuscaDePedido_StatusPav(string numero, string statusPav, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT18"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Melhorias na busca de pedido - Status Pav", null, @__tags);
#line 172
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 173
    testRunner.When(string.Format("faço uma busca avançada de pedido por status pav e numero {0}, {1}", numero, statusPav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 174
    testRunner.Then(string.Format("visualizo todos os pedidos que estejam com status pav buscado {0}", statusPav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Melhorias na busca de pedido - Status Pav, \"1000109\"", new string[] {
                "chrome",
                "ConsultarPedidoCT18"}, SourceLine=177)]
        public virtual void MelhoriasNaBuscaDePedido_StatusPav_1000109()
        {
#line 172
this.MelhoriasNaBuscaDePedido_StatusPav("\"1000109\"", "\"Aprovado\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void InformacaoNaoLocalizada(string numero, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT19"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Informação não localizada", null, @__tags);
#line 181
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 182
 testRunner.When(string.Format("faço uma busca avançada de pedido por um número que não existe no sistema {0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 183
 testRunner.Then(string.Format("visualizo a mensagem de que não foram encontrados pedidos com os dados informados" +
                        " na busca {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Informação não localizada, \"1099999\"", new string[] {
                "chrome",
                "ConsultarPedidoCT19"}, SourceLine=186)]
        public virtual void InformacaoNaoLocalizada_1099999()
        {
#line 181
this.InformacaoNaoLocalizada("\"1099999\"", "\"Dados não encontratos\"", ((string[])(null)));
#line hidden
        }
        
        public virtual void VisualizacaoDeRelatorioDePedido(string numero, string produto, string episodio, string capitulo, string obra, string midiaADebitar, string sincronismo, string valorTotal, string status, string statusPav, string reprise, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "chrome",
                    "ConsultarPedidoCT20"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Visualização de Relatório de Pedido", null, @__tags);
#line 190
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
this.FeatureBackground();
#line 191
 testRunner.When(string.Format("faço uma busca avançada de pedido por número {0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 192
    testRunner.Then(string.Format("visualizo os dados do pedido no resultado da busca {0}, {1}, {2}, {3}, {4}, {5}, " +
                        "{6}, {7}, {8}, {9}, {10}", numero, produto, episodio, capitulo, obra, midiaADebitar, sincronismo, valorTotal, status, statusPav, reprise), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 193
 testRunner.And("visualizo o relatório de pagamento do pedido buscado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Visualização de Relatório de Pedido, \"1001404\"", new string[] {
                "chrome",
                "ConsultarPedidoCT20"}, SourceLine=196)]
        public virtual void VisualizacaoDeRelatorioDePedido_1001404()
        {
#line 190
this.VisualizacaoDeRelatorioDePedido("\"1001404\"", "\"Avis1816412639 Ozane1633164760\"", "\"Paulette436942029\"", "\"01\"", "\"Jonelle1677499510\"", "\"GLOBONEWS\"", "\"ABERTURA\"", "\"R$ 67,50\"", "\"Em andamento\"", "\"Não requerido\"", "\"Não\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
